-- Test file for horror.zil complete walkthrough
-- Based on horror-walkthrough.md - tests that the game is winnable

return {
	name = "Horror.zil Complete Walkthrough Test",
	modules = {
		"zork1.globals",
		"zork1.clock",
		"adventure.horror",
		"zork1.parser",
		"zork1.verbs",
		"zork1.syntax",
		"zork1.main",
	},
	commands = {
		-- Act 1: Entrance and Upper Floors
		-- Note: Object names use underscores (e.g., BRASS-PLAQUE) because ZIL hyphens
		-- are converted to underscores during Lua compilation
		{input="look",here="SANITARIUM-GATE",description="Start at Sanitarium Gate"},
		{input="examine plaque",text="blackwood",description="Learn about Blackwood Sanitarium"},
		{input="take plaque",take="BRASS-PLAQUE",description="Take the brass plaque"},
		{input="drop plaque",lose="BRASS-PLAQUE",description="Drop brass plaque (no longer needed)"},
		{input="walk north",here="SANITARIUM-ENTRANCE",description="Enter Sanitarium Entrance Hall"},
		{input="examine wallpaper",text="victorian",description="Notice the Victorian-era decay"},
		{input="walk west",here="RECEPTION-ROOM",description="Go to Reception Room"},
		{input="take key",take="BRASS-KEY",description="Take brass key from scattered papers"},
		{input="drop key",lose="BRASS-KEY",description="Drop key (optional for this walkthrough)"},
		{input="walk east",here="SANITARIUM-ENTRANCE",description="Return to Entrance Hall"},
		{input="walk north",here="OPERATING-THEATER",description="Go to Operating Theater"},
		{input="examine table",text="restraints",description="See the gruesome operating table"},
		{input="examine cabinet",text="scalpel",description="Notice the medical cabinet"},
		{input="take scalpel",take="SCALPEL",description="Take scalpel - important tool"},
		{input="take bottle",take="ETHER-BOTTLE",description="Take ether bottle"},
		{input="walk south",here="SANITARIUM-ENTRANCE",description="Return to Entrance Hall"},
		{input="walk east",here="PATIENT-WARD",description="Go to Patient Ward"},
		{input="examine beds",text="frames",description="See the deteriorated ward"},
		{input="examine door",text="chains",description="Notice chains blocking morgue"},
		{input="attack chains",global="CHAINS-CUT-FLAG",description="Cut through chains with scalpel"},
		{input="walk north",here="MORGUE",description="Enter Morgue"},
		{input="examine drawers",text="drawers",description="Find glowing contents"},
		{input="take serum",take="STRANGE-SERUM",description="Take strange glowing serum (Compound 237)"},
		{input="examine bundle",text="patient 237",description="See canvas-wrapped body"},
		{input="take journal",take="MORDECAI-JOURNAL",description="Take Dr. Mordecai's journal"},
		{input="read journal",text="mistake",description="Learn about the terrible experiment"},
		{input="drop journal",lose="MORDECAI-JOURNAL",description="Free hands by dropping journal"},
		
		-- Act 2: Basement Exploration
		{input="walk south",here="PATIENT-WARD",description="Return to Patient Ward"},
		{input="walk west",here="SANITARIUM-ENTRANCE",description="Return to Entrance Hall"},
		{input="walk down",here="BASEMENT-STAIRS",description="Descend to Basement Stairs"},
		{input="walk down",here="BASEMENT-CORRIDOR",description="Continue to Basement Corridor"},
		{input="examine pipes",text="valve",description="Notice the valve"},
		{input="turn valve with bare hands",global="VALVE-TURNED-FLAG",description="Release steam - important for later"},
		{input="walk east",here="BOILER-ROOM",description="Enter Boiler Room"},
		{input="examine boiler",text="iron",description="See the massive iron furnace"},
		{input="open boiler",flag="IRON-BOILER OPENBIT",description="Open the boiler"},
		{input="take shovel",take="COAL-SHOVEL",description="Take coal shovel"},
		{input="examine workbench",text="flashlight",description="Find tools"},
		-- {input="take flashlight",take="FLASHLIGHT",description="Take flashlight (dead batteries)"},
		{input="walk west",here="BASEMENT-CORRIDOR",description="Return to Basement Corridor"},
		{input="walk west",here="STORAGE-ROOM",description="Enter Storage Room"},
		{input="examine shelves",text="bag",description="Find supplies including medical bag"},
		{input="take bag",take="MEDICAL-BAG",description="Take medical bag"},
		{input="open bag",flag="MEDICAL-BAG OPENBIT",description="Open medical bag (already open)"},
		{input="take bandages",take="BANDAGES",description="Take bandages from bag"},
		{input="take morphine",take="MORPHINE-VIAL",description="Take morphine vial from bag"},
		{input="drop bandages",lose="BANDAGES",description="Drop bandages (optional item)"},
		{input="drop morphine",lose="MORPHINE-VIAL",description="Drop morphine vial (optional item)"},
		{input="drop bag",lose="MEDICAL-BAG",description="Drop medical bag (no longer needed)"},
		{input="take lantern",take="OIL-LANTERN",description="Take oil lantern - working light"},
		{input="light lantern",flag="OIL-LANTERN ONBIT",description="Illuminate the darkness"},
		{input="take records",take="MEDICAL-RECORDS",description="Take medical records"},
		{input="read records",text="patient 189",description="Learn about Patient 189"},
		{input="drop records",lose="MEDICAL-RECORDS",description="Drop medical records (no longer needed)"},
		{input="walk east",here="BASEMENT-CORRIDOR",description="Return to Basement Corridor"},
		{input="walk north",here="FLOODING-CHAMBER",description="Enter Flooding Chamber"},
		{input="examine water",text="cold",description="Cold ankle-deep water"},
		{input="examine door",text="steam",description="Sealed door to east - needs steam"},
		{input="open door",global="STEAM-DOOR-OPEN",description="Steam has loosened it - access Hydrotherapy"},
		{input="walk east",here="HYDROTHERAPY-ROOM",description="Enter Hydrotherapy Room"},
		{input="examine tubs",text="notebook",description="Find notebook"},
		{input="take notebook",take="SOGGY-NOTEBOOK",description="Take soggy notebook"},
		{input="read notebook",text="water",description="Learn about water torture"},
		{input="drop notebook",lose="SOGGY-NOTEBOOK",description="Drop soggy notebook (no longer needed)"},
		{input="examine cabinet",text="syringe",description="Medicine cabinet"},
		{input="take syringe",take="SYRINGE",description="Take syringe"},
		{input="walk west",here="FLOODING-CHAMBER",description="Return to Flooding Chamber"},
		{input="walk north",here="ISOLATION-WARD",description="Enter Isolation Ward"},
		{input="examine doors",text="metal",description="See the cell doors"},
		{input="examine scratches",text="chapel",description="Critical clue: PATIENT 189 STILL ALIVE IN THE CHAPEL"},
		{input="walk north",here="ELECTROSHOCK-THEATER",description="Enter Electroshock Theater"},
		{input="examine chair",text="restraints",description="The terrible shock chair"},
		{input="examine machine",text="voltage",description="Electroshock equipment"},
		{input="walk west",here="PADDED-CELL",description="Enter Padded Cell"},
		{input="examine padding",text="189",description="Blood message about chapel and Patient 189"},
		{input="take jacket",take="STRAITJACKET",description="Take straitjacket (optional)"},
		{input="drop jacket",lose="STRAITJACKET",description="Drop straitjacket (optional item, not needed)"},
		{input="walk east",here="ELECTROSHOCK-THEATER",description="Return to Electroshock Theater"},
		
		-- Act 3: Administrative Wing and Final Confrontation
		{input="walk east",here="OBSERVATION-DECK",description="Climb to Observation Deck"},
		{input="examine mirror",text="theater",description="One-way mirror overlooking theater"},
		{input="take logbook",take="OBSERVATION-LOGBOOK",description="Take observation logbook"},
		{input="read logbook",text="189",description="Learn about Patient 189's treatment"},
		{input="drop logbook",lose="OBSERVATION-LOGBOOK",description="Drop observation logbook (no longer needed)"},
		{input="walk north",here="ADMINISTRATIVE-WING",description="Enter Administrative Wing"},
		{input="examine papers",text="189",description="Find memo about Patient 189 and chapel"},
		{input="walk east",here="DIRECTORS-OFFICE",description="Enter Director's Office"},
		{input="examine portrait",text="mordecai",description="See Dr. Heinrich Mordecai's portrait"},
		{input="examine desk",text="key",description="Find hidden compartment"},
		{input="take key",take="SAFE-KEY",description="Take safe key"},
		{input="examine safe",text="locked",description="Notice wall safe"},
		{input="unlock safe with key",flag="WALL-SAFE OPENBIT",description="Open safe with safe key"},
		{input="drop key",lose="SAFE-KEY",description="Drop safe key (no longer needed)"},
		{input="take notes",take="MORDECAI-NOTES",description="Take Dr. Mordecai's private notes"},
		{input="read notes",text="transcended",description="Learn Patient 189 transcended death"},
		{input="drop notes",lose="MORDECAI-NOTES",description="Drop Dr. Mordecai's notes (no longer needed)"},
		{input="take chapel key",take="CHAPEL-KEY",description="Take chapel key (iron key with cross)"},
		{input="walk west",here="ADMINISTRATIVE-WING",description="Return to Administrative Wing"},
		{input="walk north",here="STAFF-QUARTERS",description="Enter Staff Quarters"},
		{input="examine lockers",text="photograph",description="Find personal items"},
		{input="take photograph",take="PHOTOGRAPH",description="Take staff photo from 1950"},
		{input="examine photograph",text="1950",description="See the sanitarium staff"},
		{input="drop photograph",lose="PHOTOGRAPH",description="Drop staff photograph (no longer needed)"},
		{input="walk west",here="CAFETERIA",description="Enter Cafeteria"},
		{input="examine counter",text="bell",description="Old service area"},
		{input="take bell",take="BELL",description="Take service bell (optional)"},
		{input="drop bell",lose="BELL",description="Drop service bell (optional item, not needed)"},
		{input="walk north",here="OVERGROWN-GARDEN",description="Enter Overgrown Garden"},
		{input="examine garden",text="dead",description="Wild tangle of dead plants"},
		{input="examine door",text="hope",description="Chapel door with ominous message"},
		{input="unlock door with key",global="CHAPEL-UNLOCKED",description="Use chapel key to unlock final area"},
		{input="walk north",here="CHAPEL",description="Enter Chapel - Final Location"},
		{input="examine pews",text="symbols",description="Strange carved symbols"},
		{input="examine candles",text="green",description="Unnatural green flames"},
		{input="examine box",text="altar",description="Wooden box beneath altar"},
		{input="open box",flag="WOODEN-BOX OPENBIT",description="Pry open box with scalpel"},
		{input="take relic",take="ANCIENT-RELIC",description="Take ancient silver relic from box"},
		{input="examine relic",text="symbols",description="Cross with writhing symbols"},
		{input="drop relic",lose="ANCIENT-RELIC",description="Drop relic (optional item)"},
		{input="drop scalpel",lose="SCALPEL",description="Drop scalpel (no longer needed)"},
		{input="examine patient",text="189",description="Patient 189 - Dr. Mordecai's achievement"},
		{input="hello",description="WIN CONDITION - Patient 189 speaks and crumbles to ash"}
	}
}
