<DIRECTIONS NORTH SOUTH>
<CONSTANT RELEASEID 1>

<OBJECT ADVENTURER
        (DESC "you")
        (SYNONYM ADVENTURER ME SELF)
        (FLAGS)>

<ROUTINE TEST-SETUP (ROOM-OBJ)
    <SETG HERE .ROOM-OBJ>
    <SETG LIT T>
    <SETG WINNER ,ADVENTURER>
    <SETG PLAYER ,WINNER>
    <MOVE ,ADVENTURER ,HERE>>

<ROOM STARTROOM
      (IN ROOMS)
      (DESC "Start Room")
      (LDESC "A test room.")
      (FLAGS RLANDBIT ONBIT)>

<OBJECT APPLE
        (IN STARTROOM)
        (SYNONYM APPLE)
        (DESC "apple")
        (FLAGS TAKEBIT)>


<ROUTINE RUN-TEST ()
    <TELL "Testing basic ASSERT functionality..." CR CR>
    
    <ASSERT "ADVENTURER object exists" ,ADVENTURER>
    
    <TEST-SETUP ,STARTROOM>
    <ASSERT "ADVENTURER at STARTROOM after TEST-SETUP" <==? <LOC ,ADVENTURER> ,STARTROOM>>
    <ASSERT "HERE is STARTROOM" <==? ,HERE ,STARTROOM>>
    
    <ASSERT "Apple in STARTROOM" <==? <LOC ,APPLE> ,STARTROOM>>
    <MOVE ,APPLE ,ADVENTURER>
    <ASSERT "Apple in inventory" <==? <LOC ,APPLE> ,ADVENTURER>>
    
    <TELL CR "All tests completed!" CR>>
