<INSERT-FILE "zork1/globals">
<INSERT-FILE "zork1/clock">

<DIRECTIONS NORTH SOUTH>
<CONSTANT RELEASEID 1>

<OBJECT ADVENTURER (DESC "you") (SYNONYM ADVENTURER) (FLAGS)>
<ROOM TESTROOM (DESC "Test") (LDESC "Test") (FLAGS RLANDBIT ONBIT)>

<GLOBAL TEST-FIRED 0>

<ROUTINE TEST-DEMON ()
  <SETG TEST-FIRED <+ ,TEST-FIRED 1>>
  <TELL "DEMON FIRED! TEST-FIRED=" N ,TEST-FIRED CR>
  T>

<ROUTINE RUN-TEST ()
  <TELL "Starting demon test" CR>
  <SETG TEST-FIRED 0>
  <TELL "TEST-FIRED=" N ,TEST-FIRED CR>
  
  <LET ((D <INT ,TEST-DEMON T>))
    <TELL "Created demon, entry=" N .D CR>
    <TELL "Enabling demon..." CR>
    <ENABLE .D>
    <TELL "Queuing with tick=2..." CR>
    <QUEUE ,TEST-DEMON 2>
    
    <TELL "First CLOCKER..." CR>
    <CLOCKER>
    <TELL "After first CLOCKER, TEST-FIRED=" N ,TEST-FIRED CR>
    
    <TELL "Second CLOCKER..." CR>
    <CLOCKER>
    <TELL "After second CLOCKER, TEST-FIRED=" N ,TEST-FIRED CR>>
  
  <TELL "Test complete!" CR>>

<ROUTINE GO ()
  <SETG HERE ,TESTROOM>
  <SETG LIT T>
  <SETG WINNER ,ADVENTURER>
  <SETG PLAYER ,ADVENTURER>
  <MOVE ,ADVENTURER ,HERE>
  <RUN-TEST>>

<GLOBAL CO <CO-CREATE GO>>
