-- Test file for Zork I walkthrough
-- Based on standard Zork I walkthrough - tests major game progression
-- This walkthrough covers the main quest to collect the 20 treasures

return {
	name = "Zork I Complete Walkthrough Test",
	files = {
		"zork1/globals.zil",
		"zork1/dungeon.zil",
		"zork1/actions.zil",
		"zork1/clock.zil",
		"zork1/parser.zil",
		"zork1/verbs.zil",
		"zork1/syntax.zil",
		"zork1/main.zil",
	},
	commands = {
		-- Part 1: West of House and Initial Exploration
		{input="look",here="WEST-OF-HOUSE",description="Start at West of House"},
		{input="examine house",text="colonial",description="Examine the white house"},
		{input="open mailbox",flag="MAILBOX OPENBIT",description="Open the mailbox"},
		{input="take leaflet",take="LEAFLET",description="Take the leaflet from mailbox"},
		{input="read leaflet",text="adventure",description="Read the welcome leaflet"},
		{input="drop leaflet",lose="LEAFLET",description="Drop leaflet (no longer needed)"},
		
		-- Part 2: Entering the House
		{input="north",here="NORTH-OF-HOUSE",description="Go to North of House"},
		{input="open window",flag="WINDOW OPENBIT",description="Open the window"},
		{input="enter",here="KITCHEN",description="Enter house through window"},
		{input="take lamp",take="BRASS-LANTERN",description="Take the brass lantern"},
		{input="open trap door",flag="TRAP-DOOR OPENBIT",description="Open the trap door in kitchen"},
		{input="turn on lamp",flag="BRASS-LANTERN ONBIT",description="Turn on the brass lantern"},
		
		-- Part 3: Cellar and Trophy Case
		{input="down",here="CELLAR",description="Descend into the cellar"},
		{input="examine case",text="trophy",description="Examine the trophy case"},
		{input="east",here="EAST-OF-CHASM",description="Go east to chasm"},
		{input="north",here="GALLERY",description="Go north to gallery"},
		
		-- Part 4: Troll Area
		{input="west",here="STUDIO",description="Go west to studio"},
		{input="take painting",take="PAINTING",description="Take the painting (treasure 1)"},
		{input="east",here="GALLERY",description="Return to gallery"},
		{input="south",here="EAST-OF-CHASM",description="Go south"},
		{input="northeast",here="ROUND-ROOM",description="Go northeast to round room"},
		{input="east",here="LOUD-ROOM",description="Go east to loud room"},
		{input="up",here="DEEP-CANYON",description="Go up to deep canyon"},
		{input="west",here="RESERVOIR-SOUTH",description="Go west to reservoir south"},
		{input="west",here="RESERVOIR",description="Go west to reservoir"},
		{input="north",here="RESERVOIR-NORTH",description="Go north to reservoir north"},
		{input="examine boat",text="boat",description="Examine the boat"},
		{input="take boat",take="BOAT",description="Take the boat"},
		{input="launch",here="STREAM-VIEW",description="Launch boat (enter boat)"},
		{input="wait",description="Wait for current to carry boat"},
		{input="wait",description="Continue waiting"},
		{input="wait",description="Continue waiting"},
		{input="land",here="SANDY-BEACH",description="Land boat at sandy beach"},
		{input="north",here="SANDY-CAVE",description="Go north to sandy cave"},
		{input="take scarab",take="SCARAB",description="Take the scarab (treasure 2)"},
		{input="northeast",here="SHORE",description="Go northeast to shore"},
		{input="south",here="ARAGAIN-FALLS",description="Go south to Aragain Falls"},
		{input="take pot",take="POTTERY",description="Take the pot of gold (treasure 3)"},
		
		-- Part 5: Rainbow and Sceptre
		{input="west",here="END-OF-RAINBOW",description="Go west to End of Rainbow"},
		{input="drop pot",lose="POTTERY",description="Drop pot here"},
		{input="open bag",flag="RAINBOW-BAG OPENBIT",description="Open the rainbow bag"},
		{input="wave sceptre",description="Wave the sceptre to create rainbow"},
		{input="drop sceptre",lose="SCEPTRE",description="Drop sceptre"},
		{input="take pot",take="POTTERY",description="Take pot again"},
		
		-- Part 6: Return to Trophy Case with Treasures
		{input="east",here="ARAGAIN-FALLS",description="Return to Aragain Falls"},
		{input="west",here="RESERVOIR-SOUTH",description="Go west"},
		{input="south",here="DEEP-CANYON",description="Go south"},
		{input="down",here="LOUD-ROOM",description="Go down"},
		{input="west",here="ROUND-ROOM",description="Go west"},
		{input="southwest",here="EAST-OF-CHASM",description="Go southwest"},
		{input="west",here="CELLAR",description="Return to cellar"},
		{input="put painting in case",description="Put painting in trophy case"},
		{input="put scarab in case",description="Put scarab in trophy case"},
		{input="put pot in case",description="Put pot in trophy case"},
		
		-- Part 7: Maze and Cyclops Area
		{input="east",here="EAST-OF-CHASM",description="Go back east"},
		{input="northeast",here="ROUND-ROOM",description="Go northeast"},
		{input="southeast",here="ENGRAVINGS-CAVE",description="Go southeast to engravings cave"},
		{input="east",here="DOME-ROOM",description="Go east to dome room"},
		{input="down",here="TORCH-ROOM",description="Go down to torch room"},
		{input="south",here="TEMPLE",description="Go south to temple"},
		{input="east",here="EGYPTIAN-ROOM",description="Go east to Egyptian room"},
		{input="take coffin",take="COFFIN",description="Take the coffin (treasure 4)"},
		{input="west",here="TEMPLE",description="Return to temple"},
		{input="north",here="TORCH-ROOM",description="Go north"},
		{input="east",here="NORTH-SOUTH-PASSAGE",description="Go east to passage"},
		{input="north",here="CHASM-ROOM",description="Go north to chasm room"},
		{input="northeast",here="RESERVOIR-SOUTH",description="Cross chasm"},
		{input="south",here="DEEP-CANYON",description="Go south"},
		{input="down",here="LOUD-ROOM",description="Go down"},
		{input="west",here="ROUND-ROOM",description="Go west"},
		{input="southwest",here="EAST-OF-CHASM",description="Go southwest"},
		{input="west",here="CELLAR",description="Return to cellar"},
		{input="put coffin in case",description="Put coffin in trophy case"},
		
		-- Part 8: Getting the Sword and More Treasures
		{input="up",here="KITCHEN",description="Go up to kitchen"},
		{input="west",here="LIVING-ROOM",description="Go west to living room"},
		{input="take sword",take="SWORD",description="Take the elvish sword"},
		{input="take rug",take="RUG",description="Take the rug"},
		{input="examine rug",text="dust",description="Notice dust on rug"},
		{input="move rug",flag="TRAP-DOOR OPENBIT",description="Move rug to reveal trap door"},
		{input="down",here="CELLAR",description="Go down through trap door"},
		{input="east",here="EAST-OF-CHASM",description="Go east"},
		{input="northeast",here="ROUND-ROOM",description="Go northeast"},
		{input="southeast",here="ENGRAVINGS-CAVE",description="Go southeast"},
		{input="east",here="DOME-ROOM",description="Go east"},
		{input="down",here="TORCH-ROOM",description="Go down"},
		{input="south",here="TEMPLE",description="Go south"},
		{input="south",here="ALTAR",description="Go south to altar"},
		{input="pray",description="Pray at the altar"},
		{input="take candles",take="CANDLES",description="Take the candles (treasure 5)"},
		{input="south",here="CAVE-SOUTH",description="Go south"},
		{input="west",here="MIRROR-ROOM-SOUTH",description="Go west to mirror room"},
		{input="north",here="MIRROR-ROOM-NORTH",description="Go north in mirror room"},
		{input="west",here="WINDING-PASSAGE",description="Go west to winding passage"},
		{input="north",here="CAVE-NORTH",description="Go north"},
		{input="west",here="ENTRANCE-TO-HADES",description="Go west to entrance to Hades"},
		{input="down",here="LAND-OF-LIVING-DEAD",description="Descend to Land of Living Dead"},
		{input="examine altar",text="sacrifices",description="Examine the sacrifices"},
		{input="take book",take="BOOK",description="Take the black book"},
		{input="read book",text="prayers",description="Read the prayers"},
		
		-- Part 9: Back to Trophy Case
		{input="up",here="ENTRANCE-TO-HADES",description="Return to entrance"},
		{input="east",here="CAVE-NORTH",description="Go east"},
		{input="south",here="WINDING-PASSAGE",description="Go south"},
		{input="east",here="MIRROR-ROOM-NORTH",description="Go east"},
		{input="south",here="MIRROR-ROOM-SOUTH",description="Go south"},
		{input="east",here="CAVE-SOUTH",description="Go east"},
		{input="north",here="ALTAR",description="Go north"},
		{input="north",here="TEMPLE",description="Go north"},
		{input="north",here="TORCH-ROOM",description="Go north"},
		{input="up",here="DOME-ROOM",description="Go up"},
		{input="west",here="ENGRAVINGS-CAVE",description="Go west"},
		{input="northwest",here="ROUND-ROOM",description="Go northwest"},
		{input="southwest",here="EAST-OF-CHASM",description="Go southwest"},
		{input="west",here="CELLAR",description="Return to cellar"},
		{input="put candles in case",description="Put candles in trophy case"},
		
		-- Part 10: Exploring More Areas - Coal Mine
		{input="east",here="EAST-OF-CHASM",description="Go east"},
		{input="northeast",here="ROUND-ROOM",description="Go northeast"},
		{input="east",here="LOUD-ROOM",description="Go east"},
		{input="down",here="DAMP-CAVE",description="Go down to damp cave"},
		{input="west",here="WHITE-CLIFFS-BEACH-SOUTH",description="Go west to white cliffs"},
		{input="southwest",here="SANDY-BEACH",description="Go southwest to sandy beach"},
		{input="south",here="SANDY-CAVE",description="Go south"},
		{input="west",here="SHORE",description="Go west"},
		{input="west",here="PUMPING-STATION",description="Go west to pumping station"},
		{input="examine switch",text="switch",description="Examine the switch"},
		
		-- Part 11: Mine and More Treasures
		{input="north",here="COAL-MINE-1",description="Go north to coal mine"},
		{input="northeast",here="COAL-MINE-2",description="Continue in mine"},
		{input="southeast",here="COAL-MINE-3",description="Continue in mine"},
		{input="south",here="COAL-MINE-4",description="Continue in mine"},
		{input="down",here="LADDER-BOTTOM",description="Go down ladder"},
		{input="north",here="LADDER-TOP",description="Go north"},
		{input="west",here="TIMBER-ROOM",description="Go west to timber room"},
		{input="examine timber",text="timber",description="Examine the timber"},
		{input="drop all",description="Drop everything to reduce weight"},
		{input="take lamp",take="BRASS-LANTERN",description="Just take lamp"},
		{input="south",here="DRAFTY-ROOM",description="Go south to drafty room"},
		{input="take bar",take="PLATINUM-BAR",description="Take platinum bar (treasure 6)"},
		
		-- Part 12: Return and Deposit
		{input="north",here="TIMBER-ROOM",description="Return to timber room"},
		{input="take all",description="Take all items back"},
		{input="east",here="LADDER-TOP",description="Go east"},
		{input="south",here="LADDER-BOTTOM",description="Go south"},
		{input="up",here="COAL-MINE-4",description="Go up"},
		{input="north",here="COAL-MINE-3",description="Go north in mine"},
		{input="northwest",here="COAL-MINE-2",description="Go northwest"},
		{input="southwest",here="COAL-MINE-1",description="Go southwest"},
		{input="south",here="PUMPING-STATION",description="Return to pumping station"},
		{input="east",here="SHORE",description="Go east"},
		{input="east",here="SANDY-CAVE",description="Go east"},
		{input="north",here="SANDY-BEACH",description="Go north"},
		{input="northeast",here="WHITE-CLIFFS-BEACH-SOUTH",description="Go northeast"},
		{input="east",here="DAMP-CAVE",description="Go east"},
		{input="up",here="LOUD-ROOM",description="Go up"},
		{input="west",here="ROUND-ROOM",description="Go west"},
		{input="southwest",here="EAST-OF-CHASM",description="Go southwest"},
		{input="west",here="CELLAR",description="Return to cellar"},
		{input="put bar in case",description="Put platinum bar in trophy case"},
		
		-- Part 13: Final Areas and Treasures
		{input="east",here="EAST-OF-CHASM",description="Go east"},
		{input="northeast",here="ROUND-ROOM",description="Go northeast"},
		{input="north",here="NORTH-SOUTH-PASSAGE",description="Go north"},
		{input="north",here="CHASM-ROOM",description="Go north"},
		{input="northeast",here="RESERVOIR-SOUTH",description="Go northeast"},
		{input="south",here="DEEP-CANYON",description="Go south"},
		{input="southeast",here="ATLANTIS-ROOM",description="Go southeast to Atlantis room"},
		{input="take trident",take="TRIDENT",description="Take the trident (treasure 7)"},
		{input="northwest",here="DEEP-CANYON",description="Return to canyon"},
		{input="down",here="LOUD-ROOM",description="Go down"},
		{input="west",here="ROUND-ROOM",description="Go west"},
		{input="southwest",here="EAST-OF-CHASM",description="Go southwest"},
		{input="west",here="CELLAR",description="Return to cellar"},
		{input="put trident in case",description="Put trident in trophy case"},
		
		-- Note: This is a partial walkthrough covering the early-to-mid game treasures
		-- A complete walkthrough would continue with all 20 treasures and solving
		-- remaining puzzles (thief, endgame, etc.)
	}
}
