-- Extended tests for Zork1
-- This test file demonstrates more complex command sequences
-- Based on the commented-out tests from the original bootstrap.lua

return {
	name = "Zork1 Extended Tests",
	files = {
		"zork1/globals.zil",
		"zork1/clock.zil",
		"zork1/parser.zil",
		"zork1/verbs.zil",
	  "zork1/actions.zil",
  	"zork1/syntax.zil",
  	"zork1/dungeon.zil",
	  "zork1/actions.zil",
		"zork1/main.zil",
	},
	commands = {
		{ input="open mailbox", text="Opening the small mailbox reveals a leaflet." },
		{ input="read leaflet", text="(Taken)" },
		{ input="drop leaflet", text="Dropped." },
		{ input="walk south", text="South of House" },
		{ input="walk east", text="Behind House" },
		{ input="open window", text="With great effort, you open the window far enough to allow entry." },
		{ input="enter house", text="Kitchen" },
		{ input="walk west", text="Living Room" },
		{ input="take lamp", text="Taken." },
		{ input="move rug", text="With a great effort, the rug is moved to one side of the room, revealing the dusty cover of a closed trap door." },
		{ input="open trap door", text="The door reluctantly opens to reveal a rickety staircase descending into darkness." },
		{ input="turn on lamp", text="The brass lantern is now on." },
		{ input="walk down", text="The trap door crashes shut, and you hear someone barring it." },
		{ input="walk south", text="East of Chasm" },
		{ input="walk east", text="Gallery" },
		{ input="take painting", text="Taken." },
		{ input="walk north", text="Studio" },
		{ input="walk up chimney", text="Kitchen" },
		{ input="walk up", text="Attic" },
		{ input="take knife", text="Taken." },
		{ input="take rope", text="Taken." },
		{ input="walk down", text="Kitchen" },
		{ input="walk west", text="Living Room" },
		{ input="open case", text="Opened." },
		{ input="put painting inside case", text="Done." },
		{ input="drop knife", text="Dropped." },
		{ input="take sword", text="Taken." },
		{ input="open trap door", text="The door reluctantly opens to reveal a rickety staircase descending into darkness." },
		{ input="walk down", text="The trap door crashes shut, and you hear someone barring it." },
		{ input="walk north", text="The Troll Room" },
		{ input="kill troll with sword", description="" },
		{ input="kill troll with sword", description="" },
		{ input="kill troll with sword", description="" },
		{ input="kill troll with sword", description="" },
		{ input="kill troll with sword", description="" },
		{ input="kill troll with sword", global="TROLL-FLAG", description="The troll is knocked out!" },
		{ input="drop sword", description="Drop sword if present" },
		-- { input="kill troll with sword", text="You are still recovering from that last blow, so your attack is ineffective." },
		-- { input="kill troll with sword", text="Clang! Crash! The troll parries." },
		-- { input="kill troll with sword", text="The troll is confused and can't fight back." },
		-- { input="kill troll with sword", text="The troll is knocked out!" },
		-- { input="kill troll with sword", text="The unarmed troll cannot defend himself: He dies." },
		-- { input="drop sword", text="Dropped." },
		{ input="walk east", text="East-West Passage" },
		{ input="walk east", text="Round Room" },
		{ input="walk southe", text="Engravings Cave" },
		{ input="walk east", text="Dome Room" },
		{ input="tie rope to railing", text="The rope drops over the side and comes within ten feet of the floor." },
		{ input="walk down", text="Torch Room" },
		{ input="walk south", text="Temple" },
		{ input="walk east", text="Egyptian Room" },
		{ input="take coffin", text="Taken." },
		{ input="walk west", text="Temple" },
		{ input="walk south", text="Altar" },
		{ input="pray", text="Forest" },
		{ input="turn off lamp", text="The brass lantern is now off." },
		{ input="walk south", text="Forest" },
		{ input="walk north", text="Clearing" },
		{ input="walk east", text="Canyon View" },
		{ input="walk down", text="Rocky Ledge" },
		{ input="walk down", text="Canyon Bottom" },
		{ input="walk north", text="End of Rainbow" },
		{ input="drop coffin", text="Dropped." },
		{ input="open coffin", text="The gold coffin opens." },
		{ input="take sceptre", text="Taken." },
		{ input="wave sceptre", text="Suddenly, the rainbow appears to become solid and, I venture, walkable (I think the giveaway was the stairs and bannister)." },
		{ input="take gold", text="Taken." },
		{ input="take coffin", text="Taken." },
		{ input="walk southwest", text="Canyon Bottom" },
		{ input="walk up", text="Rocky Ledge" },
		{ input="walk up", text="Canyon View" },
		{ input="walk northwest", text="Clearing" },
		{ input="walk west", text="Behind House" },
		{ input="enter house", text="Kitchen" },
		{ input="open bag", text="Opening the brown sack reveals a lunch, and a clove of garlic." },
		{ input="take garlic", text="Taken." },
		{ input="walk west", text="Living Room" },
		{ input="put coffin in case", text="Done." },
		{ input="put gold in case", text="Done." },
		{ input="put sceptre in case", text="Done." },
		{ input="open trap door", text="The door reluctantly opens to reveal a rickety staircase descending into darkness." },
		{ input="turn on lamp", text="The brass lantern is now on." },
		{ input="walk down", text="Cellar" },
		{ input="walk north", text="The Troll Room" },
		{ input="walk east", text="East-West Passage" },
		{ input="walk north", text="Chasm" },
		{ input="walk northe", text="Reservoir South" },
		{ input="walk east", text="Dam" },
		{ input="walk north", text="Dam Lobby" },
		{ input="take matches", text="Taken." },
		{ input="walk north", text="Maintenance Room" },
		{ input="take wrench", text="Taken." },
		{ input="take screwdriver", text="Taken." },
		{ input="push yellow button", text="Click." },
		{ input="walk south", text="Dam Lobby" },
		{ input="walk south", text="Dam" },
		{ input="turn bolt with wrench", text="The sluice gates open and water pours through the dam." },
		{ input="drop wrench", text="Dropped." },
		{ input="walk south", text="Deep Canyon" },
		{ input="walk down", text="Loud Room" },
		{ input="walk southe", text="Engravings Cave", start="ROUND-ROOM" },
		{ input="walk east", text="Dome Room" },
		{ input="walk down", text="Torch Room" },
		{ input="take torch", text="Taken." },
		{ input="turn off lamp", text="The brass lantern is now off." },
		{ input="walk south", text="Temple" },
		{ input="take bell", text="Taken." },
		{ input="walk south", text="Altar" },
		{ input="take candles", text="Taken." },
		{ input="take book", text="Taken." },
		{ input="walk down", text="Cave" },
		{ input="walk down", text="Entrance to Hades" },
		{ input="ring bell", text="The bell suddenly becomes red hot and falls to the ground. The wraiths, as if paralyzed, stop their jeering and slowly turn to face you. On their ashen faces, the expression of a long-forgotten terror takes shape." },
		{ input="take candles", text="Taken." },
		{ input="light match", text="One of the matches starts to burn." },
		{ input="light candles with match", text="The candles are lit." },
		{ input="read book", text="Each word of the prayer reverberates through the hall in a deafening confusion." },
		{ input="drop book", text="Dropped." },
		{ input="walk south", text="Land of the Dead" },
		{ input="take skull", text="Taken." },
		{ input="walk north", text="Entrance to Hades" },
		{ input="walk up", text="Cave" },
		{ input="walk north", text="Mirror Room" },
		{ input="rub mirror", text="There is a rumble from deep within the earth and the room shakes." },
		{ input="walk north", text="Cold Passage" },
		{ input="walk west", text="Slide Room" },
		{ input="walk north", text="Mine Entrance" },
		{ input="walk west", text="Squeaky Room" },
		{ input="inventory", text="You are carrying:" },
		{ input="walk north", text="Bat Room" },
		{ input="walk east", text="Shaft Room" },
		{ input="put torch in basket", text="Done." },
		{ input="put screwdriver in basket", text="Done." },
		{ input="turn on lamp", text="The brass lantern is now on." },
		{ input="walk north", text="Smelly Room" },
		{ input="walk down", text="Gas Room" },
		{ input="walk east", text="Coal Mine" },
		{ input="walk northe", text="Coal Mine" },
		{ input="walk southe", text="Coal Mine" },
		{ input="walk southwest", text="Coal Mine" },
		{ input="walk down", text="Ladder Top" },
		{ input="walk down", text="Ladder Bottom" },
		{ input="walk south", text="Dead End" },
		{ input="take coal", text="Taken." },
		{ input="walk north", text="Ladder Bottom" },
		{ input="walk up", text="Ladder Top" },
		{ input="walk up", text="Coal Mine" },
		{ input="walk north", text="Coal Mine" },
		{ input="walk east", text="Coal Mine" },
		{ input="walk south", text="Coal Mine" },
		{ input="walk north", text="Gas Room" },
		{ input="walk up", text="Smelly Room" },
		{ input="walk south", text="Shaft Room" },
		{ input="put coal in basket", text="Done." },
		{ input="lower basket", text="The basket is lowered to the bottom of the shaft." },
		{ input="walk north", text="Smelly Room" },
		{ input="walk down", text="Gas Room" },
		{ input="walk east", text="Coal Mine" },
		{ input="walk northe", text="Coal Mine" },
		{ input="walk southe", text="Coal Mine" },
		{ input="walk southwest", text="Coal Mine" },
		{ input="walk down", text="Ladder Top" },
		{ input="walk down", text="Ladder Bottom" },
		{ input="walk west", text="Timber Room" },
		{ input="drop all", text="crystal skull: Dropped." },
		{ input="walk west", text="Drafty Room" },
		{ input="take coal", text="Taken." },
		{ input="take screwdriver", text="Taken." },
		{ input="take torch", text="Taken." },
		{ input="walk south", text="Machine Room" },
		{ input="open lid", text="The lid opens." },
		{ input="put coal in machine", text="Done." },
		{ input="close lid", text="The lid closes." },
		{ input="turn switch with screwdriver", text="The machine comes to life (figuratively) with a dazzling display of colored lights and bizarre noises. After a few moments, the excitement abates." },
		{ input="drop screwdriver", text="Dropped." },
		{ input="open lid", text="The lid opens, revealing a huge diamond." },
		{ input="take diamond", text="Taken." },
		{ input="walk north", text="Drafty Room" },
		{ input="put torch in basket", text="Done." },
		{ input="put diamond in basket", text="Done." },
		{ input="walk east", text="Timber Room" },
		{ input="take skull", text="Taken." },
		{ input="take lamp", text="Taken." },
		{ input="take garlic", text="Taken." },
		{ input="walk east", text="Ladder Bottom" },
		{ input="walk up", text="Ladder Top" },
		{ input="walk up", text="Coal Mine" },
		{ input="walk north", text="Coal Mine" },
		{ input="walk east", text="Coal Mine" },
		{ input="walk south", text="Coal Mine" },
		{ input="walk north", text="Gas Room" },
		{ input="take bracelet", text="Taken." },
		{ input="walk up", text="Smelly Room" },
		{ input="walk south", text="Shaft Room" },
		{ input="raise basket", text="The basket is raised to the top of the shaft." },
		{ input="look in basket", text="The basket contains:" },
		{ input="take diamond", text="Taken." },
		{ input="take torch", text="Taken." },
		{ input="turn off lamp", text="The brass lantern is now off." },
		{ input="walk west", text="Bat Room" },
		{ input="take jade", text="Taken." },
		{ input="walk south", text="Squeaky Room" },
		{ input="walk east", text="Mine Entrance" },
		{ input="walk south", text="Slide Room" },
		{ input="walk down", text="Cellar" },
		{ input="walk up", text="Living Room" },
		{ input="inventory", text="You are carrying:" },
		{ input="put jade in case", text="Done." },
		{ input="put diamond in case", text="Done." },
		{ input="turn on lamp", text="The brass lantern is now on." },
		{ input="walk down", text="Cellar" },
		{ input="walk north", text="The Troll Room" },
		{ input="walk east", text="East-West Passage" },
		{ input="walk north", text="Chasm" },
		{ input="walk northe", text="Reservoir South" },
		{ input="walk north", text="Reservoir" },
		{ input="take trunk", text="Taken." },
		{ input="walk north", text="Reservoir North" },
		{ input="take pump", text="Taken." },
		{ input="take pump", text="Taken." },
		{ input="walk north", text="Atlantis Room" },
		{ input="take trident", text="Your load is too heavy." },
		{ input="inventory", text="You are carrying:" },
		{ input="drop torch", text="Dropped." },
		{ input="take trident", text="Taken." },
		{ input="walk south", text="Reservoir North" },
		{ input="walk south", text="Reservoir" },
		{ input="walk south", text="Reservoir South" },
		{ input="walk east", text="Dam" },
		{ input="walk east", text="Dam Base" },
		-- replaced command to use new INFLATE syntax
		{ input="inflat plastic with pump", text="The boat inflates and appears seaworthy." },
		{ input="drop pump", text="Dropped." },
		{ input="walk inside boat", text="You are now in the magic boat." },
		{ input="launch", text="(magic boat)" },
		{ input="wait", text="Time passes..." },
		{ input="wait", text="Time passes..." },
		{ input="wait", text="Time passes..." },
		{ input="wait", text="Time passes..." },
		{ input="take buoy", text="Taken." },
		{ input="walk east", text="The magic boat comes to a rest on the shore." },
		{ input="leave boat", text="You are on your own feet again." },
		{ input="take shovel", text="Your load is too heavy." },
		{ input="drop garlic", text="Dropped." },
		{ input="take shovel", text="Your load is too heavy." },
		{ input="drop buoy", text="Dropped." },
		{ input="take shovel", text="Taken." },
		{ input="walk northe", text="Sandy Cave" },

		-- { input="dig", text="What do you want to dig in?" },
		-- { input="sand", text="(with the shovel)" },
		-- { input="dig sand", text="(with the shovel)" },
		-- { input="dig sand", text="(with the shovel)" },
		-- { input="dig sand", text="(with the shovel)" },
		-- { input="take scarab", text="Taken." },
		-- { input="drop shovel", text="Dropped." },

		{ input="dig", text="What do you want to dig?" },
		{ input="sand", text="( the shovel)" },
		{ input="dig sand", text="( the shovel)" },
		{ input="dig sand", text="( the shovel)" },
		{ input="dig sand", text="( the shovel)" },
		{ input="drop shovel", text="Dropped." },
		{ input="take scarab", text="Taken." },

		{ input="walk southwest", text="Sandy Beach" },
		{ input="open buoy", text="Opening the red buoy reveals a large emerald." },
		{ input="take emerald", text="Taken." },
		{ input="take garlic", text="Taken." },
		{ input="walk south", text="Shore" },
		{ input="walk south", text="Aragain Falls" },
		{ input="cross rainbow", text="End of Rainbow" },
		{ input="turn off lamp", text="The brass lantern is now off." },
		{ input="walk southwest", text="Canyon Bottom" },
		{ input="walk up", text="Rocky Ledge" },
		{ input="walk up", text="Canyon View" },
		{ input="walk northwest", text="Clearing" },
		{ input="walk west", text="Behind House" },
		{ input="enter house", text="Kitchen" },
		{ input="walk west", text="Living Room" },
		{ input="inventory", text="You are carrying:" },
		{ input="put emerald in case", text="Done." },
		{ input="put scarab in case", text="Done." },
		{ input="put trident in case", text="Done." },
		{ input="put jewels in case", text="Done." },
		{ input="walk east", text="Kitchen" },
		{ input="walk east", text="Behind House" },
		{ input="walk north", text="North of House" },
		{ input="walk north", text="Forest Path" },
		{ input="climb tree", text="Up a Tree" },
		{ input="take egg", text="Taken." },
		{ input="climb down", text="(down the tree)" },
		{ input="walk south", text="North of House" },
		{ input="walk east", text="Behind House" },
		{ input="enter house", text="Kitchen" },
		{ input="walk west", text="Living Room" },
		{ input="turn on lamp", text="The brass lantern is now on." },
		{ input="walk down", text="Cellar" },
		{ input="walk north", text="The Troll Room" },
		{ input="walk west", text="Maze" },
		{ input="walk south", text="Maze" },
		{ input="walk east", text="Maze" },
		{ input="walk up", text="Maze" },
		{ input="take coins", text="Taken." },
		{ input="take key", text="Taken." },
		{ input="walk southwest", text="Maze" },
		{ input="walk east", text="Maze" },
		{ input="walk south", text="Maze" },
		{ input="walk southe", text="Cyclops Room" },
		{ input="Ulysses", text="The cyclops, hearing the name of his father's deadly nemesis, flees the room by knocking down the wall on the east of the room." },
		{ input="give egg to thief", text="The thief is taken aback by your unexpected generosity, but accepts the jewel-encrusted egg and stops to admire its beauty." },
		{ input="walk down", text="Cyclops Room" },
		{ input="walk east", text="Strange Passage" },
		{ input="walk east", text="Living Room" },
		{ input="put coins in case", text="Done." },
		{ input="take knife", text="Taken." },
		{ input="walk west", text="Strange Passage" },
		{ input="walk west", text="Cyclops Room" },
		{ input="walk up", text="You hear a scream of anguish as you violate the robber's hideaway. Using passages unknown to you, he rushes to its defense." },
		{ input="kill thief with knife", text="The thief is disarmed by a subtle feint past his guard." },
		{ input="kill thief with knife", text="You dodge as the thief comes in low." },
		{ input="kill thief with knife", text="It's curtains for the thief as your nasty knife removes his head." },
		{ input="take all", text="stiletto: Taken." },
		{ input="drop stiletto", text="Dropped." },
		{ input="take chalice", text="You're holding too many things already!" },
		{ input="drop torch", text="Dropped." },
		{ input="take chalice", text="Taken." },
		{ input="walk down", text="Cyclops Room" },
		{ input="walk northwest", text="Maze" },
		{ input="walk south", text="Maze" },
		{ input="walk west", text="Maze" },
		{ input="walk up", text="Maze" },
		{ input="walk down", text="You won't be able to get back up to the tunnel you are going through when it gets to the next room." },
		{ input="walk northe", text="Grating Room" },
		{ input="unlock grate", text="(with the skeleton key)" },
		{ input="open grate", text="The grating opens to reveal trees above you." },
		{ input="walk up", text="Clearing" },
		{ input="walk south", text="Forest Path" },
		{ input="climb tree", text="Up a Tree" },
		{ input="wind up canary", text="The canary chirps, slightly off-key, an aria from a forgotten opera. From out of the greenery flies a lovely songbird. It perches on a limb just over your head and opens its beak to sing. As it does so a beautiful brass bauble drops from its mouth, bounces off the top of your head, and lands glimmering in the grass. As the canary winds down, the songbird flies away." },
		{ input="walk down", text="Forest Path" },
		{ input="take bauble", text="You're holding too many things already!" },
		{ input="drop knife", text="Dropped." },
		{ input="take bauble", text="Taken." },
		{ input="walk south", text="North of House" },
		{ input="walk east", text="Behind House" },
		{ input="enter house", text="Kitchen" },
		{ input="walk west", text="Living Room" },
		{ input="put bauble in case", text="Done." },
		{ input="put chalice in case", text="Done." },
		{ input="take canary from egg", text="Taken." },
		{ input="put canary in case", text="Done." },
		{ input="put egg in case", text="Done." },
		{ input="put bracelet in case", text="Done." },
		{ input="put skull in case", text="Done." },
		{ input="walk down", text="Cellar" },
		{ input="walk north", text="The Troll Room" },
		{ input="walk east", text="East-West Passage" },
		{ input="walk east", text="Round Room" },
		{ input="walk east", text="Loud Room" },
		{ input="echo", text="The acoustics of the room change subtly." },
		{ input="take bar", text="Taken." },
		{ input="walk west", text="Round Room" },
		{ input="walk west", text="East-West Passage" },
		{ input="walk west", text="The Troll Room" },
		{ input="walk south", text="Cellar" },
		{ input="walk up", text="Living Room" },
		{ input="put bar in case", text="Done" },

	}
}
