"PLANETFALL for
			       PLANETFALL
	  (c) COPYRIGHT 1983 INFOCOM INC. ALL RIGHTS RESERVED"

<VERSION ZIP>
<FREQUENT-WORDS?>
<SET REDEFINE T>
<SETG NEW-VOC? T>	;"allows words to be adj/noun/verb all at once!"

<OR <GASSIGNED? ZILCH>
    <SETG WBREAKS <STRING !\" !\= !,WBREAKS>>>

<PRINC "Planetfall

">

<INSERT-FILE "SYNTAX">
<INSERT-FILE "MISC">
<INSERT-FILE "GLOBALS">
<INSERT-FILE "PARSER">
<INSERT-FILE "VERBS">
<INSERT-FILE "COMPONE">
<INSERT-FILE "COMPTWO">

<PROPDEF SIZE 5>
<PROPDEF CAPACITY 0>
<PROPDEF VALUE 0>
